name: "Veracode Auto Baseline"
description: "This action Will attempt to automatically store and download baseline files for Veracode SAST"
author: "Andy Sutcliffe - Wasptree"

inputs:
  token:
    description: "Github Access Token"
    required: true
  source:
    description: "Name of the repository where the baseline will be stored."
    required: false
  file:
    description: "Specify the name of the results/baseline file (json) to read in"
    required: false
  commit:
    description: "Custom commit message"
    required: false
  branch:
    description: "Override the default ref, which is the branch name"
    required: false
  repo:
    description: "Overrise the defaut repository, which is taken from the Github environment"
    required: false
  checkbf:
    description: "Check if the baseline file to be pushed is new (less than 10 minutes old)"
    required: false
  update:
    description: "Whether a new baseline file should be pushed up to the repository"
    required: false

runs:
  using: "docker"
  image: "docker://wasptree/veracode-autobaseline:latest"
  args: [
    "--token", "${{ inputs.token }}",
    "--source", "${{ inputs.source }}",
    "--file", "${{ inputs.file }}",
    "--commit", "${{ inputs.commit }}",
    "--branch", "${{ inputs.branch }}",
    "--repo", "${{ inputs.repo }}",
    "--checkbf", "${{ inputs.checkbf }}",
    "--update", "${{ inputs.update }}"
  ]