name: "Veracode Auto Baseline"
description: "This action Will attempt to automatically store and download baseline files for Veracode SAST"
author: "Andy Sutcliffe - Wasptree"

inputs:
  baseline_token:
    description: "Github Access Token"
    required: true
  source:
    description: "Name of the repository where the baseline will be stored. - Default <owner>/veracode-baseline"
    required: false
  result_file:
    description: "Specify the name of the results/baseline file (json) to read in - Default results.json"
    required: false
  commit:
    description: "Custom commit message"
    required: false
  branch:
    description: "Override the default ref, which is the branch name"
    required: false
  repo:
    description: "Override the defaut repository - Default is $GITHUB_REPOSITORY"
    required: false
  checkbf:
    description: "Check if the baseline file to be pushed is new (less than 10 minutes old) - Default True"
    required: false
  update:
    description: "Whether a new baseline file should be pushed up to the repository - Default False"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
